### PR TITLE
Please accept this pull request, and update pods.

### PR DESCRIPTION
**Pull request by donly**
Many thanks!

### CODE REVIEW

**Review by stubbornnessness — COMMENTED** [review]
thanks

**Comment by stubbornnessness** [comment]
有兴趣加入EasySWift组织么

**Comment by donly** [comment]
@stubbornnessness 有什么我能帮得上忙的？

**Comment by stubbornnessness** [comment]
有兴趣就加入EasySwift组织，qq群 542916901

**Pull request merged**
